### ISSUE TITLE
특정 날짜 혹은 단일 기사 불러오기

### ISSUE THREAD

**Issue by tkddnr1022** [jchanho99/AI_NES#15]
### 문제점
[뉴스 전체 목록 가져오기 API](https://www.notion.so/2080b1b4dc074fadb30351c82c14f439?v=7976ff5aeee341faafcc614fb8eaf192&pvs=4) 
현재까지 크롤링된 뉴스 기사들이 모두 Realtime DB에 저장되어 있으나, API를 호출하는 당일의 데이터를 제외하면 이전 날짜의 데이터는 불러올 수 없습니다.
또한 단일 뉴스 기사를 불러오는 것이 불가능합니다.

### 제안
getData request body에 `date`와 `index` 추가
- `date`: 불러올 날짜 (기본값: 당일 날짜)
- `index`: 불러올 인덱스 (기본값: undefined)
- 특정 날짜와 인덱스에 해당하는 기사를 반환
- `index`=`undefined` 일 경우 기존처럼 30개를 모두 반환

혹은 이를 충족할 수 있는 별도의 엔드포인트 구현

### 이점
Realtime DB에 저장된 뉴스 기사들을 웹페이지에 모두 활용할 수 있고, 특정 단일 기사에 대한 접근이 가능해져 URL 공유가 가능합니다.

**Comment by xchxn** [comment]
기존 Get요청과 다르게
Post로 /api/getData 요청시
Body에 date만 들어오는 경우 / index만 들어오는 경우 / date와 index 둘 다 들어 오는 경우로 나누어서 구현해놨습니다!
