### ISSUE TITLE
news_data 파라미터 정의

### ISSUE THREAD

**Issue by tkddnr1022** [jchanho99/AI_NES#24]
### 필드 범주 정의
Realtime DB의 news_data 에서 `section` 필드와 `sentiment` 필드에 어떤 값들이 포함될 수 있는지 범주를 알고 싶습니다.
`section` 필드는 raw 데이터를 실제 서비스에서는 생활, 문화, 경제와 같이 보다 직접적으로 표현하기 위해 한글 매핑에 참조할 범주가 필요합니다.
`sentiment` 필드 또한 감정을 표현하는 어떠한 컨텐츠를 구상하는데에 범주가 필요합니다. 어떠한 값들이 반환될 수 있는지 알면 좀 더 유연하게 구현이 가능할 것 같습니다.

**Comment by MyungKyuKim** [comment]
section_list = [("politics", "100"), ("economics", "101"), ("social", "102"), ("culture", "103"), ("worlds","104"), ("Tech", "105")]
네 기존 section 분류는 다음과 같이 되어 있었습니다. 해당 내용에서 한글매핑에 참조할 범주가 필요하다고 하신부분이 잘 이해가 가지 않아 답변을 좀 더 구체화 하여 말씀드리겠습니다.

혹시 말씀하시는 이슈 부분이 위 section list에서 아래와 같이 기존 영어로 되어있던 section을 한글로 매핑하면 해결되시는 부분인지 궁금합니다.아래와 같이 변경하면, realtimeDB에 올라가는 section 에 매핑되는 value 가 경제, 사회, 문화, 세계, 기술 로 분류됩니다. (politics section 은 교수님께서  정치적 이슈를 제외하라고 하셔서 없앨 예정이라 다음과 같이 보내드립니다.)
    section_list = [("경제", "101"), ("사회", "102"), ("문화", "103"), ("세계","104"), ("기술", "105")]

**Comment by tkddnr1022** [comment]
확인하였습니다! 단순히 페이지상에서 카테고리를 한글로 표기하기 위해 반환될수 있는 값의 종류를 알고자 하였습니다. 

말씀하신것처럼 크롤링 단계에서 카테고리가 한글로 저장되도록 해주시면 좋을것 같습니다.

**Comment by MyungKyuKim** [comment]
6월 8일 데이터부터 위 코멘트에서 말씀드린 것과 같이 올라갑니다.
