### ISSUE TITLE
뉴스 요약 간결성 향상 제안

### ISSUE THREAD

**Issue by tkddnr1022** [jchanho99/AI_NES#25]
## 문제
![image](https://github.com/jchanho99/AI_NES/assets/56585709/ec44bf40-f08a-4790-ba25-62f7e8b7bb64)
위와 같이 뉴스 기사의 `summary`값이 너무 길어 페이지에서 가독성을 확보하는 데에 어려움이 있습니다.
flowbite 컴포넌트의 dom 특성상 z-index 조절만으로는 overflow를 방지하기 어려워 깔끔한 UI를 보여주기 힘든 문제도 있습니다.

## 제안
`summary`값을 더 간결하게 생성하여 짧은 길이의 요약을 제공하면 사용자 경험 측면에서 이점이 있을 것 같습니다.
위 예시의 요약본 길이가 457자인데, 200~300자 길이의 요약본을 생성하면 어떤가 싶습니다.

**Comment by MyungKyuKim** [comment]
200 자 이내의 text length 로 제약을 둘 수 있도록 Prompt에 추가하도록 하겠습니다. 감사합니다.
